"""Add maintenance_id to inventory requests

Revision ID: 3e5463d29981
Revises: ebead5244def
Create Date: 2025-10-30 02:53:23.343919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5463d29981'
down_revision = 'ebead5244def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_request_maintenance', 'maintenance_record', ['maintenance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_request_maintenance', type_='foreignkey')
        batch_op.drop_column('maintenance_id')

    # ### end Alembic commands ###
