"""add last_ranking_update to game

Revision ID: 7a61de1d1679
Revises: b547f37c117c
Create Date: 2025-11-11 14:54:39.480761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a61de1d1679'
down_revision = 'b547f37c117c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_ranking_update', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('last_ranking_update')

    # ### end Alembic commands ###
