"""Add tracking fields to inventory requests

Revision ID: 8dcea35845db
Revises: e7582856b8aa
Create Date: 2025-10-30 04:09:35.394465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcea35845db'
down_revision = 'e7582856b8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tracking_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tracking_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_tracking_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_request', schema=None) as batch_op:
        batch_op.drop_column('last_tracking_update')
        batch_op.drop_column('tracking_details')
        batch_op.drop_column('tracking_status')
        batch_op.drop_column('carrier')

    # ### end Alembic commands ###
