"""Add work_order_type column to maintenance_record

Revision ID: b547f37c117c
Revises: 8dcea35845db
Create Date: 2025-10-30 22:32:39.420108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b547f37c117c'
down_revision = '8dcea35845db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_order_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location_description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.drop_column('location_description')
        batch_op.drop_column('work_order_type')

    # ### end Alembic commands ###
