"""Device, rail_session, reading; and where a maintenance order came from.

Phase 2: the one-way channel from GATBOX. A device authenticates with a bearer token and
posts metered sessions, their downsampled traces, and maintenance orders raised at the
bench. See contract/v1/README.md for the wire format.

Hand-written rather than autogenerated, and guarded per object, because this has to be
safe on two databases that are not in the same state: the live PostgreSQL arrived at its
schema through migrations, while a fresh test database is built by ``db.create_all()`` and
stamped. A guard-free ``create_table`` fails on the second.

``reading.rail_session_id`` gets the schema's first non-unique index. Drawing a trace is
"every reading for this session, in order", over the largest table in the application --
roughly two thousand rows per session.

Revision ID: d4e5f6a7b8c9
Revises: f1c2d3e4a5b6
"""

import sqlalchemy as sa
from alembic import op

revision = "d4e5f6a7b8c9"
down_revision = "f1c2d3e4a5b6"
branch_labels = None
depends_on = None


def _has_table(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _has_column(table: str, column: str) -> bool:
    if not _has_table(table):
        return False
    return column in {c["name"] for c in sa.inspect(op.get_bind()).get_columns(table)}


def upgrade():
    if not _has_table("device"):
        op.create_table(
            "device",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=60), nullable=False),
            sa.Column("public_id", sa.String(length=32), nullable=False),
            sa.Column("token_hash", sa.String(length=256), nullable=False),
            sa.Column("enabled", sa.Boolean(), nullable=False),
            sa.Column("created", sa.DateTime(), nullable=True),
            sa.Column("last_seen", sa.DateTime(), nullable=True),
            sa.Column("last_ip", sa.String(length=45), nullable=True),
            sa.Column("notes", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_device")),
            sa.UniqueConstraint("name", name=op.f("uq_device_name")),
            sa.UniqueConstraint("public_id", name=op.f("uq_device_public_id")),
        )

    if not _has_table("rail_session"):
        op.create_table(
            "rail_session",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("uid", sa.String(length=32), nullable=False),
            sa.Column("device_id", sa.Integer(), nullable=False),
            sa.Column("game_id", sa.Integer(), nullable=True),
            sa.Column("file", sa.String(length=64), nullable=False),
            sa.Column("started", sa.DateTime(), nullable=True),
            sa.Column("ended", sa.DateTime(), nullable=True),
            sa.Column("duration_s", sa.Float(), nullable=True),
            sa.Column("samples", sa.Integer(), nullable=True),
            sa.Column("rate", sa.Float(), nullable=True),
            sa.Column("timebase", sa.String(length=30), nullable=True),
            sa.Column("clock", sa.String(length=12), nullable=True),
            sa.Column("clock_ntp_from", sa.DateTime(), nullable=True),
            sa.Column("profile_id", sa.String(length=40), nullable=True),
            sa.Column("profile_label", sa.String(length=60), nullable=True),
            sa.Column("profile_kind", sa.String(length=10), nullable=True),
            sa.Column("rail", sa.String(length=10), nullable=True),
            sa.Column("mode", sa.String(length=10), nullable=True),
            sa.Column("window_lo", sa.Float(), nullable=True),
            sa.Column("window_hi", sa.Float(), nullable=True),
            sa.Column("window_unit", sa.String(length=8), nullable=True),
            sa.Column("window_source", sa.String(length=40), nullable=True),
            sa.Column("alarm_hi", sa.Float(), nullable=True),
            sa.Column("powered_mean", sa.Float(), nullable=True),
            sa.Column("powered_min", sa.Float(), nullable=True),
            sa.Column("powered_max", sa.Float(), nullable=True),
            sa.Column("powered_readings", sa.Integer(), nullable=True),
            sa.Column("in_window_pct", sa.Float(), nullable=True),
            sa.Column("verdict", sa.String(length=10), nullable=True),
            sa.Column("verdict_detail", sa.Text(), nullable=True),
            sa.Column("over_voltage", sa.Integer(), nullable=True),
            sa.Column("excursions", sa.Integer(), nullable=True),
            sa.Column("power_cycles", sa.Integer(), nullable=True),
            sa.Column("gaps", sa.Integer(), nullable=True),
            sa.Column("ol_events", sa.Integer(), nullable=True),
            sa.Column("marks", sa.Integer(), nullable=True),
            sa.Column("suspect", sa.Integer(), nullable=True),
            sa.Column("received", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(
                ["device_id"], ["device.id"], name=op.f("fk_rail_session_device_id")
            ),
            sa.ForeignKeyConstraint(
                ["game_id"], ["game.id"], name=op.f("fk_rail_session_game_id")
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_rail_session")),
            sa.UniqueConstraint("uid", name=op.f("uq_rail_session_uid")),
        )

    if not _has_table("reading"):
        op.create_table(
            "reading",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("uid", sa.String(length=32), nullable=False),
            sa.Column("rail_session_id", sa.Integer(), nullable=False),
            sa.Column("epoch", sa.Float(), nullable=False),
            sa.Column("up", sa.Float(), nullable=True),
            sa.Column("v", sa.Float(), nullable=True),
            sa.Column("raw", sa.String(length=16), nullable=True),
            sa.Column("unit", sa.String(length=8), nullable=True),
            sa.Column("mode", sa.String(length=10), nullable=True),
            sa.Column("alarm", sa.String(length=6), nullable=True),
            sa.Column("ol", sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(
                ["rail_session_id"], ["rail_session.id"],
                name=op.f("fk_reading_rail_session_id"),
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_reading")),
            sa.UniqueConstraint("uid", name=op.f("uq_reading_uid")),
        )
        op.create_index(
            op.f("ix_reading_rail_session_id"), "reading", ["rail_session_id"],
            unique=False,
        )

    # maintenance_record: three columns, each guarded separately so a partially-applied
    # state still converges rather than failing on the first one that already exists.
    if not _has_column("maintenance_record", "external_id"):
        with op.batch_alter_table("maintenance_record", schema=None) as batch_op:
            batch_op.add_column(sa.Column("external_id", sa.String(length=64), nullable=True))
            batch_op.create_unique_constraint(
                op.f("uq_maintenance_record_external_id"), ["external_id"]
            )
    if not _has_column("maintenance_record", "source"):
        with op.batch_alter_table("maintenance_record", schema=None) as batch_op:
            batch_op.add_column(sa.Column("source", sa.String(length=20), nullable=True))
        # Every row that exists predates this channel, so it came from the web app.
        op.execute("UPDATE maintenance_record SET source = 'web' WHERE source IS NULL")
    if not _has_column("maintenance_record", "rail_session_id"):
        with op.batch_alter_table("maintenance_record", schema=None) as batch_op:
            batch_op.add_column(sa.Column("rail_session_id", sa.Integer(), nullable=True))
            batch_op.create_foreign_key(
                op.f("fk_maintenance_record_rail_session_id"),
                "rail_session", ["rail_session_id"], ["id"],
            )


def downgrade():
    if _has_column("maintenance_record", "rail_session_id"):
        with op.batch_alter_table("maintenance_record", schema=None) as batch_op:
            batch_op.drop_constraint(
                op.f("fk_maintenance_record_rail_session_id"), type_="foreignkey"
            )
            batch_op.drop_column("rail_session_id")
    if _has_column("maintenance_record", "source"):
        with op.batch_alter_table("maintenance_record", schema=None) as batch_op:
            batch_op.drop_column("source")
    if _has_column("maintenance_record", "external_id"):
        with op.batch_alter_table("maintenance_record", schema=None) as batch_op:
            batch_op.drop_constraint(
                op.f("uq_maintenance_record_external_id"), type_="unique"
            )
            batch_op.drop_column("external_id")
    if _has_table("reading"):
        op.drop_index(op.f("ix_reading_rail_session_id"), table_name="reading")
        op.drop_table("reading")
    if _has_table("rail_session"):
        op.drop_table("rail_session")
    if _has_table("device"):
        op.drop_table("device")
