"""Add tracking_number vendor and estimated_arrival to InventoryRequest

Revision ID: e7582856b8aa
Revises: 3e5463d29981
Create Date: 2025-10-30 03:07:21.536383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7582856b8aa'
down_revision = '3e5463d29981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('estimated_arrival', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_request', schema=None) as batch_op:
        batch_op.drop_column('estimated_arrival')
        batch_op.drop_column('vendor')
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
