"""Add priority field to maintenance records

Revision ID: ebead5244def
Revises: 5a026e6869ec
Create Date: 2025-10-30 02:30:23.604778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebead5244def'
down_revision = '5a026e6869ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
